### ISSUE TITLE
Reaction Roles

### ISSUE THREAD

**Issue by Thinjon100** [fossilz/falcobot#1]
We'll want some analogue of reaction roles so that we can retain the self-signup aspect for notifications.

**Comment by Thinjon100** [comment]
we'll need to store the configuration for the trigger condition to assign the role.  Simplest would be "if user reacts to any message in {channel} with {emoji} give them {role}"

**Comment by sentienceee** [comment]
Possibly use a queue system alongside a user timeout to reduce bot ratelimiting and spamming the reactions for roles
