### ISSUE TITLE
Dynamic Voice/Text Channels

### ISSUE THREAD

**Issue by TWest3D** [fossilz/falcobot#16]
Have the bot auto add a role to members who join certain voice channels that will allow them to see an associated text channel. This will be useful for coordinating things while playing games, etc. The channels/roles in question will not allow the members to see history, and it will look like they join a "fresh" channel every time. The mods will still be able to see history. Once the member leaves the voice channel, the role will be removed, and they will lose access to the channel.

**Comment by Thinjon100** [comment]
Added setChannelAutoRole command - sets channel auto role ID in db
Added voiceStateUpdate event - if channel being joined has auto role ID, apply.  if channel being left has auto role ID, remove
